# Generated by Django 2.2.5 on 2020-01-06 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_friendgroup_friendgroupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='access_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.FriendGroup'),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('all_friends', 'All Friends'), ('friend_group', 'Friend Group')], default='private', max_length=20),
            preserve_default=False,
        ),
    ]
