version: "3"
services:
  app:
    build: .
    environment:
      DB_NAME: posts
      DB_HOST: database
      DB_USER: posts
      DB_PASS: password
      DJANGO_SETTINGS_MODULE: posts.settings.local
      DJANGO_SECRET_KEY: secret
      PASSWORDLESS_EMAIL_NOREPLY_ADDRESS: noreply@example.com
      WEB_ORIGIN: 'http://localhost:3000'
    command: scripts/docker-start
    ports:
    - "8000:8000"
    volumes:
    - .:/usr/src/app/
    depends_on:
    - database
  database:
    image: postgres
    environment:
      POSTGRES_USER: posts
      POSTGRES_DB: posts
      POSTGRES_PASSWORD: password
    volumes:
        - db-data:/var/lib/postgresql/data
volumes:
  db-data: